version: "2.4"
volumes:
  caddy_config:
  caddy_data:
  ntfy_config:
  ntfy_cache:
  ntfy_lib:
services:
  
  caddy:
    build:
      context: ./caddy
      args:
      - DNS_PROVIDER=digitalocean
      - CADDY_VERSION=v2.5.2
    environment:
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/data
      - CADDY_VERSION=v2.5.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  ntfy:
    image: binwiederhier/ntfy
    command: 
      - serve
    environment:
      - TZ=America/Los_Angeles
      - NTFY_LISTEN_HTTP=127.0.0.1:8256
      - NTFY_BASE_URL=https://ntfy.sameureka.dev
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_CACHE_DURATION=24h
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_BEHIND_PROXY=true
      - NTFY_AUTH_FILE=/var/lib/ntfy/user.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_ENABLE_LOGIN=true
    volumes:
      - ntfy_config:/etc/ntfy
      - ntfy_cache:/var/cache/ntfy 
      - ntfy_lib:/var/lib/ntfy
    ports:
      - 8256:8256
    restart: unless-stopped
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'