version: "2.4"
volumes:
  youTrackData:
  youTrackBack:
  youTrackLogs:
  youTrackConf:
  caddy_config:
  caddy_data:
services:
  caddy:
    build:
      context: ./caddy
      args:
      - DNS_PROVIDER=digitalocean
      - CADDY_VERSION=v2.5.2
    environment:
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/data
      - CADDY_VERSION=v2.5.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  youTrack:
    image: jetbrains/youtrack:2023.3.22912
    ports: 
      - "8080:8080"
    volumes:
      - youTrackData:/opt/youtrack/data/
      - youTrackConf:/opt/youtrack/conf/
      - youTrackLogs:/opt/youtrack/logs/
      - youTrackBack:/opt/youtrack/backups/
    labels:
      io.balena.features.dbus: '1'
